// Generated by Xata Codegen 0.30.1. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {BaseClientOptions} from "@xata.io/client";


export type DatabaseSchema = {};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://cyras0-s-workspace-r01me4.us-west-2.xata.sh/db/snapcast",
    apiKey: process.env.XATA_API_KEY,
    branch: "main",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    if (!process.env.XATA_API_KEY) {
      throw new Error('XATA_API_KEY is not defined');
    }
    super({ ...defaultOptions, ...options });
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  if (!process.env.XATA_API_KEY) {
    throw new Error('XATA_API_KEY is not defined');
  }

  instance = new XataClient();
  return instance;
};
